# .github/workflows/terraform-cicd.yml

name: Terraform CI/CD

on:
  workflow_dispatch:  # Allows manual trigger only

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production  # Or your target environment

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.1  # Specify the Terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        continue-on-error: true  # Continues execution even if the plan fails

      #- name: Terraform Apply
        #run: terraform apply -auto-approve

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

